name: LPTeamSync
version: 1.0.0
author: ArmouredMonkey
main: io.github.armouredmonkey.LPTeamSync
depend: [LuckPerms]
api-version: 1.13

commands:
  lpts-reload:
    description: Reloads the configuration
    permission: lpteamsync.reload
    usage: /lpts-reload