name: LPTeamSync
version: 1.0.0
author: ArmouredMonkey
main: io.github.armouredmonkey.LPTeamSync
depend: [LuckPerms]
softdepend: [WorldGuard, PlaceholderAPI]
api-version: 1.13

commands:
  extracontexts-reload:
    description: Reloads the configuration
    permission: extracontexts.reload
    usage: /extracontexts-reload